# Generated by Django 4.2.17 on 2024-12-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email Address")),
                ("phone", models.CharField(max_length=15, verbose_name="Phone Number")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                ("postal_code", models.CharField(max_length=20, verbose_name="Postal Code")),
                ("country", models.CharField(default="United States", max_length=100, verbose_name="Country")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping",
                        to="product.cart",
                        verbose_name="Cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Total Price")),
                (
                    "delivery_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Delivery Charge"),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Shipped", "Shipped"), ("Delivered", "Delivered")],
                        default="Pending",
                        max_length=20,
                        verbose_name="Order Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="product.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "shipping",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="product.shipping",
                        verbose_name="Shipping",
                    ),
                ),
            ],
        ),
    ]
