# Generated by Django 4.2.17 on 2025-01-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cartitem_free_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='free_cases',
        ),
        migrations.AddField(
            model_name='cart',
            name='free_cases',
            field=models.PositiveIntegerField(default=0, verbose_name='Free Cases'),
        ),
    ]
