# Generated by Django 4.2.17 on 2025-01-02 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('business_address', models.TextField(verbose_name='Business Address')),
                ('business_city', models.CharField(max_length=255, verbose_name='City')),
                ('business_state', models.CharField(help_text='Use standard 2-letter state code, e.g. CA, NY, TX, etc.', max_length=2, verbose_name='State (US)')),
                ('business_zip', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('business_phone', models.CharField(max_length=50, verbose_name='Business Phone')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
