# Generated by Django 4.2.17 on 2025-01-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
